package db

import (
	"fmt"
	"io"
	"strings"
	"time"
)

// ExportOptions configures how the SQL dump is generated.
type ExportOptions struct {
	// IncludeCreate emits CREATE TABLE statements before the data.
	IncludeCreate bool
	// DropIfExists emits DROP TABLE IF EXISTS before each CREATE TABLE.
	DropIfExists bool
	// NoData skips INSERT statements (schema-only export).
	NoData bool
	// Output is the destination writer for the SQL dump.
	Output io.Writer
	// Progress is the destination writer for status messages (e.g. os.Stderr).
	Progress io.Writer
}

// ExportSQL exports one or all tables from the given connection as a SQL dump.
// If tables is empty, all tables are exported.
func ExportSQL(
	conn DatabaseConnection,
	tables []string,
	opts ExportOptions,
) error {
	if opts.Output == nil {
		return fmt.Errorf("export: Output writer is required")
	}
	if opts.Progress == nil {
		opts.Progress = io.Discard
	}

	if len(tables) == 0 {
		var err error
		tables, err = conn.GetTables()
		if err != nil {
			return fmt.Errorf("could not list tables: %w", err)
		}
	}

	// Write dump header
	fmt.Fprintf(opts.Output, "-- SQL Dump generated by pam\n")
	fmt.Fprintf(opts.Output, "-- Connection : %s\n", conn.GetName())
	fmt.Fprintf(opts.Output, "-- Database   : %s\n", conn.GetDbType())
	fmt.Fprintf(
		opts.Output,
		"-- Generated  : %s\n",
		time.Now().Format(time.RFC3339),
	)
	fmt.Fprintf(opts.Output, "-- Tables     : %d\n", len(tables))
	fmt.Fprintf(opts.Output, "\n")

	for i, tableName := range tables {
		fmt.Fprintf(
			opts.Progress,
			"[%d/%d] Exporting table: %s\n",
			i+1,
			len(tables),
			tableName,
		)

		if err := exportTable(conn, tableName, opts); err != nil {
			return fmt.Errorf("error exporting table %q: %w", tableName, err)
		}
	}

	fmt.Fprintf(opts.Progress, "Done. %d table(s) exported.\n", len(tables))
	return nil
}

// exportTable writes the DDL and/or data for a single table to opts.Output.
func exportTable(
	conn DatabaseConnection,
	tableName string,
	opts ExportOptions,
) error {
	fmt.Fprintf(
		opts.Output,
		"\n-- -----------------------------------------------\n",
	)
	fmt.Fprintf(opts.Output, "-- Table: %s\n", tableName)
	fmt.Fprintf(
		opts.Output,
		"-- -----------------------------------------------\n\n",
	)

	if opts.DropIfExists {
		fmt.Fprintf(opts.Output, "DROP TABLE IF EXISTS %s;\n\n", tableName)
	}

	if opts.IncludeCreate {
		ddl, err := buildCreateTableSQL(conn, tableName)
		if err != nil {
			fmt.Fprintf(
				opts.Output,
				"-- Warning: could not generate CREATE TABLE for %q: %v\n\n",
				tableName,
				err,
			)
		} else {
			fmt.Fprintf(opts.Output, "%s\n\n", ddl)
		}
	}

	if !opts.NoData {
		if err := exportTableData(conn, tableName, opts.Output); err != nil {
			return fmt.Errorf("could not export data: %w", err)
		}
	}

	return nil
}

// buildCreateTableSQL generates a portable CREATE TABLE statement for the given table.
// It uses GetColumnDetails to inspect column metadata.
func buildCreateTableSQL(
	conn DatabaseConnection,
	tableName string,
) (string, error) {
	cols, err := conn.GetColumnDetails(tableName)
	if err != nil {
		return "", fmt.Errorf("GetColumnDetails: %w", err)
	}
	if len(cols) == 0 {
		return "", fmt.Errorf("no columns found for table %q", tableName)
	}

	var parts []string
	var pkCols []string

	for _, col := range cols {
		if col.IsPrimaryKey {
			pkCols = append(pkCols, col.Name)
		}

		nullable := ""
		if col.Nullable == "NO" {
			nullable = " NOT NULL"
		}

		defaultClause := ""
		if col.DefaultValue != "" && col.DefaultValue != "NULL" {
			defaultClause = fmt.Sprintf(" DEFAULT %s", col.DefaultValue)
		}

		line := fmt.Sprintf(
			"  %s %s%s%s",
			col.Name,
			col.DataType,
			nullable,
			defaultClause,
		)
		parts = append(parts, line)
	}

	if len(pkCols) > 0 {
		parts = append(
			parts,
			fmt.Sprintf("  PRIMARY KEY (%s)", strings.Join(pkCols, ", ")),
		)
	}

	ddl := fmt.Sprintf(
		"CREATE TABLE %s (\n%s\n);",
		tableName,
		strings.Join(parts, ",\n"),
	)
	return ddl, nil
}

// exportTableData streams all rows of a table as INSERT statements.
func exportTableData(
	conn DatabaseConnection,
	tableName string,
	out io.Writer,
) error {
	query := fmt.Sprintf("SELECT * FROM %s", tableName)

	rows, err := conn.ExecQuery(query)
	if err != nil {
		return fmt.Errorf("SELECT failed: %w", err)
	}
	defer rows.Close()

	columns, columnTypes, data, err := FormatTableDataWithTypes(rows)
	if err != nil {
		return fmt.Errorf("could not read rows: %w", err)
	}

	if len(data) == 0 {
		fmt.Fprintf(out, "-- (no rows in %s)\n", tableName)
		return nil
	}

	// Quote column names generically with double-quotes (standard SQL).
	quotedCols := make([]string, len(columns))
	for i, c := range columns {
		quotedCols[i] = quoteIdentifier(c)
	}
	colList := strings.Join(quotedCols, ", ")

	for _, row := range data {
		values := make([]string, len(row))
		for i, val := range row {
			dbType := ""
			if i < len(columnTypes) {
				dbType = columnTypes[i]
			}
			values[i] = formatSQLValue(val, dbType)
		}
		fmt.Fprintf(out, "INSERT INTO %s (%s) VALUES (%s);\n",
			tableName,
			colList,
			strings.Join(values, ", "),
		)
	}

	return nil
}

// formatSQLValue converts a string-formatted cell value into a proper SQL literal.
// It uses the database column type name to decide whether to quote the value.
func formatSQLValue(val, dbTypeName string) string {
	if val == "NULL" {
		return "NULL"
	}

	upperType := strings.ToUpper(dbTypeName)

	if isNumericType(upperType) {
		// Sanity-check: make sure the value actually looks numeric before
		// emitting it unquoted. If not, fall through to the string path.
		if looksNumeric(val) {
			return val
		}
	}

	if isBooleanType(upperType) {
		switch strings.ToUpper(val) {
		case "TRUE", "1", "T", "YES":
			return "TRUE"
		case "FALSE", "0", "F", "NO":
			return "FALSE"
		}
	}

	// Default: treat as a string literal — escape single quotes.
	escaped := strings.ReplaceAll(val, "'", "''")
	return fmt.Sprintf("'%s'", escaped)
}

// isNumericType returns true when the database type name represents a numeric
// value that should be emitted without quotes in SQL.
func isNumericType(upperType string) bool {
	numericPrefixes := []string{
		"INT", "INTEGER", "BIGINT", "SMALLINT", "TINYINT", "MEDIUMINT",
		"INT2", "INT4", "INT8",
		"FLOAT", "FLOAT4", "FLOAT8",
		"DOUBLE", "REAL",
		"DECIMAL", "NUMERIC", "NUMBER",
		"MONEY", "SMALLMONEY",
		"BIT",
	}
	for _, prefix := range numericPrefixes {
		if upperType == prefix || strings.HasPrefix(upperType, prefix+"(") {
			return true
		}
	}
	return false
}

// isBooleanType returns true when the database type name represents a boolean.
func isBooleanType(upperType string) bool {
	return upperType == "BOOL" || upperType == "BOOLEAN"
}

// looksNumeric returns true when s can be interpreted as a numeric literal.
func looksNumeric(s string) bool {
	if s == "" {
		return false
	}
	dotSeen := false
	eSeen := false
	for i, ch := range s {
		switch {
		case ch >= '0' && ch <= '9':
			// digit — always OK
		case ch == '-' || ch == '+':
			if i != 0 && !eSeen {
				return false
			}
		case ch == '.':
			if dotSeen {
				return false
			}
			dotSeen = true
		case ch == 'e' || ch == 'E':
			if eSeen {
				return false
			}
			eSeen = true
		default:
			return false
		}
	}
	return true
}

// quoteIdentifier wraps an identifier in double-quotes, escaping any
// double-quotes inside (standard SQL identifier quoting).
func quoteIdentifier(name string) string {
	escaped := strings.ReplaceAll(name, `"`, `""`)
	return fmt.Sprintf(`"%s"`, escaped)
}
